/*
 * This Scala source file was generated by the Gradle 'init' task.
 */
package ScalaTowerDefense

import Logger.LogHelper

object App extends LogHelper {
  def main(args: Array[String]): Unit = {
    logger.info(greeting())
    logger.error("This is an error")
    logger.debug("Debug logging")
  }

  def greeting(): String = "Hello, world!"
}
